title: STEMCraft Academy by SEPIA
email: info@stemcraftacademy.com
description: >
  STEMCraft Academy by SEPIA offers innovative online STEM education through interactive learning with Minecraft Education Edition. Engage with our courses to explore, create, and learn in an immersive virtual environment.

# Assuming your GitHub Pages site is at the root
baseurl: "" 
url: "https://sepiaedu.github.io"

# Social Media and GitHub (if applicable)
twitter_username: sepiaedu
github_username: sepiaedu

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Optionally, if you have other social media or important links, you can add them here
# as custom variables and then reference them in your templates
facebook_username: sepiaedu
instagram_username: sepiaedu

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
